### ISSUE TITLE
When no REACT_APP_CHAT_GPT_API_KEY is given in the frontend .env file, the hub no longer renders and redirects to a white screen

### ISSUE THREAD

**Issue by sjenzh** [TUMFARSynchrony/SynthARium#253]
See the following screenshot for the error

![Image](https://github.com/TUMFARSynchrony/experimental-hub/assets/45497990/f32396c9-d805-49c4-96b3-af4be65392ad)

**Comment by NCEghtebas** [comment]
was this issue addressed with PR https://github.com/TUMFARSynchrony/experimental-hub/pull/245 ?
